### ISSUE TITLE
[PE-D][Tester A] Unable to handle date in other formats

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-4/tp#98] opened 2023-04-01 01:47 UTC
![Screenshot 2023-03-31 at 5.40.22 PM.png](https://raw.githubusercontent.com/ZiqiuZeng/ped/main/files/0ee1e641-46b5-4457-a5c9-c35812ce30e4.png)

![Screenshot 2023-03-31 at 5.38.36 PM.png](https://raw.githubusercontent.com/ZiqiuZeng/ped/main/files/7578e19a-37d6-4956-9f87-c08b94c85992.png)

The application cannot deal with the date parameter give in other formats, such as dd/mm/yyyy or mm/dd/yyyy, otherwise the application will crash.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ZiqiuZeng/ped#8

**Comment by varnika1402** [comment] 2023-04-10 04:32
Duplicate of #82

**Closed by varnika1402** 2023-04-10 04:32 UTC
